project_insta/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(url='/insta/', permanent=True)),
    path('insta/', include('insta.urls')),
    path('common/', include('common.urls')),








    # path('', lambda request: redirect('insta/')),

    # path('', include('photo.urls')),  # '/' 에 해당되는 path
    # path('', lambda request: redirect('photo/')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

project_insta/insta/urls.py
from django.urls import path
from insta import views, vote_views





app_name = 'insta'
urlpatterns = [


    path('', views.allPhotoAB, name='allPhotoAB'),

    path('myPhotoAB/', views.myPhotoAB, name='myPhotoAB'),
    # path('<slug:c_slug>/', views.myPhotoAB, name='myPhotoAB'),

    path('<slug:c_slug>/', views.allPhotoAB, name='album_detail'),

    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('vote/photo/<int:photo_id>/', vote_views.vote_photo, name='vote_photo'),

    path('answer/create/<int:photo_id>/', vote_views.answer_create, name='answer_create'),

    path('photo/modify/<int:photo_id>/', vote_views.photo_modify, name='photo_modify'),
    path('photo/delete/<int:photo_id>/', vote_views.photo_delete, name='photo_delete'),

    path('answer/modify/<int:answer_id>/', vote_views.answer_modify, name='answer_modify'),

    path('answer/delete/<int:answer_id>/', vote_views.answer_delete, name='answer_delete'),

    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),




    # path('<int:photo_id>/', views.detail, name='detail'),
    # # Example: /insta/album/add/
    # path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    #
    # # Example: /insta/album/change/
    # path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    #
    # # Example: /insta/album/99/update/
    # path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    #
    # # Example: /insta/album/99/delete/
    # path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    #
    # # Example: /insta/insta/add/
    # path('insta/add/', views.PhotoCV.as_view(), name='photo_add'),
    #
    # # Example: /insta/insta/change/
    # path('insta/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    #
    # # Example: /insta/insta/99/update/
    # path('insta/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    #
    # # Example: /insta/insta/99/delete/
    # path('insta/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

    # path('photo/<int:pk>/', views.PhotoDV, name='photo_detail'),

    # path('id:c_slug/id:photo_slug', views.PhotoABDetail, name = 'PhotoABDetail'),

    # path('vote/photo/<int:photo_id>/', vote_views.vote_photo, name='vote_photo'),
]

project_insta/insta/models.py
from django.db import models
from django.urls import reverse
from insta.fields import ThumbnailImageField
from common.models import User



class Album(models.Model):
    #id 프라이머리키
    objects = None
    name = models.CharField('NAME', max_length=30)
    slug = models.SlugField(max_length=250, unique=True)
    owner = models.ForeignKey('common.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('insta:album_detail', args = [self.slug])

    def __str__(self) :
        return '{}'.format(self.name)


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = ThumbnailImageField('IMAGE', upload_to='insta/%Y/%m')
    description = models.TextField('Photo Description', blank=True)

    title = models.CharField('TITLE', max_length=30, null=True)
    upload_dt = models.DateTimeField('UPLOAD DATE', auto_now_add=True)

    owner = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name='owner_photo')
    voter = models.ManyToManyField(User, related_name='voter_photo')
    modify_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return '{}'.format(self.image.name)

    def get_absolute_url(self):
        return reverse('insta:photo_detail', args = [self.id])


class Answer(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='owner_answer')
    voter = models.ManyToManyField(User, related_name='voter_answer')

project_insta/insta/forms.py
from django.forms import inlineformset_factory
from insta.models import Album, Photo, Answer
from django import forms

PhotoInlineFormSet = inlineformset_factory(Album, Photo,
                                           fields=['image', 'description',],
                                           extra=2)

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo  # 사용할 모델
        fields = ['description']
        # 'name',
        widgets = {
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'description': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

project_insta/insta/views.py
import requests
from django.views.generic import ListView, DetailView, CreateView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

import insta.models
from insta.forms import PhotoInlineFormSet
from django.shortcuts import render, get_object_or_404
from insta.models import Album, Photo
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from common.models import User











class PhotoCV(LoginRequiredMixin, CreateView, ):
    model = Photo

    login_url = '/common/login/'
    redirect_field_name = 'login'

    fields = ('album', 'image', 'description',)

    success_url = reverse_lazy('insta:allPhotoAB')


    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'].fields['album'].queryset = Album.objects.filter(owner=self.request.user)
        return context




class AlbumPhotoCV(LoginRequiredMixin, CreateView, ):
    model = Album

    login_url = '/common/login/'
    redirect_field_name = 'login'

    fields = ('name', 'slug',)
    success_url = reverse_lazy('insta:allPhotoAB')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))






# # #(안되는거 지금 이리저리 만지는중인거)
# def myPhotoAB(request, c_slug=None):
#     c_page = None
#     allphoto = request.user.id
#     photos_list = Photo.objects.filter(owner_id=allphoto)
#     if c_slug != None:
#         print(c_slug, "444444444444444444")
#         c_page = get_object_or_404(Album, slug = c_slug)
#         photos_list = Photo.objects.filter(album = c_page).order_by('-upload_dt')
#
#     else:
#         print(c_slug, "333333333333333333")
#         photos_list = Photo.objects.order_by('-upload_dt')
#     paginator = Paginator(photos_list, 12)
#
#     try:
#         page = int(request.GET.get('page', 1))
#     except:
#         page = 1
#
#     try:
#         photos = paginator.page(page)
#     except(EmptyPage, InvalidPage):
#         photos = paginator.page(paginator.num_pages)
#
#     return render(request, 'insta/myalbum.html', {'album': c_page, 'photos': photos})



# (일단은 되긴한데 좀 이상한거)
def myPhotoAB(request, c_slug=None):
    c_page = None
    photos_list = None
    if c_slug != None:
        print(c_slug, "444444444444444444")
        c_page = get_object_or_404(Album, slug = c_slug)
        photos_list = Photo.objects.filter(album = c_page).order_by('-upload_dt')

    else:
        print(c_slug, "333333333333333333")
        photos_list = Photo.objects.order_by('-upload_dt')
    paginator = Paginator(photos_list, 12)

    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1

    try:
        photos = paginator.page(page)
    except(EmptyPage, InvalidPage):
        photos = paginator.page(paginator.num_pages)

    return render(request, 'insta/myalbum.html', {'album': c_page, 'photos': photos})



def allPhotoAB(request, c_slug=None):
    c_page = None
    photos_list = None
    if c_slug != None:
        print(request.GET)
        print(c_slug, "22222222222222")
        c_page = get_object_or_404(Album, slug = c_slug)
        photos_list = Photo.objects.filter(album = c_page).order_by('-upload_dt')

    else :
        print(c_slug, "111111111111111111")
        photos_list = Photo.objects.order_by('-upload_dt')
    paginator = Paginator(photos_list, 12)

    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1

    try:
        photos = paginator.page(page)
    except(EmptyPage, InvalidPage):
        photos = paginator.page(paginator.num_pages)

    return render(request, 'insta/album.html', {'album': c_page, 'photos': photos})









# def PhotoABDetail(request, c_slug, photo_slug):
#     try:
#         photo = Photo.objects.get(album__slug = c_slug, slug = photo_slug)
#     except Exception as e :
#         raise e
#
#     return render(request, 'insta/insta.html', {'insta' : photo})










class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo



class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'insta/photo_change_list.html'
    #매니져가 지정이 안되면 object_list

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)






# class PhotoUV(OwnerOnlyMixin, UpdateView):
#     model = Photo
#     fields = ('album', 'title', 'image', 'description')
#     success_url = reverse_lazy('insta:index')
#
#
# class PhotoDelV(OwnerOnlyMixin, DeleteView):
#     model = Photo
#     success_url = reverse_lazy('insta:index')




# #--- Change-list/Delete for Album
# class AlbumChangeLV(LoginRequiredMixin, ListView):
#     model = Album
#     template_name = 'insta/album_change_list.html'
#
#     def get_queryset(self):
#         return Album.objects.filter(owner=self.request.user)


# class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
#     model = Album
#     fields = ('name', 'description')
#     success_url = reverse_lazy('insta:index')
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         if self.request.POST:
#             context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
#         else:
#             context['formset'] = PhotoInlineFormSet(instance=self.object)
#         return context
#
#     def form_valid(self, form):
#         context = self.get_context_data()
#         formset = context['formset']
#         if formset.is_valid():
#             self.object = form.save()
#             formset.instance = self.object
#             formset.save()
#             return redirect(self.get_success_url())
#         else:
#             return self.render_to_response(self.get_context_data(form=form))


# class AlbumDelV(OwnerOnlyMixin, DeleteView):
#     model = Album
#     success_url = reverse_lazy('insta:index')

project_insta/templates/insta/album.html
{% extends "base.html" %}

{% block title %}
{% if album %}
{{ album.name }} - PLATE-STUDIO
{% else %}
See Our Photos Collection - PLATE-STUDIO
{% endif %}
{% endblock %}

{% block content %}


<br>
<div>
    <h1 class="text-center my_title">BLACKVERI_0</h1>
    <br>
    <p class = "text-center">포토앨범 <br>사진을 등록해보세요</p>
</div>
<br><br>
<div class="container">
    <div class="row mx-auto">



        {% for photo in photos.object_list %}
        <div class="my_bottom_margin col-9 col-sm-6 col-md-4 col-lg-4">
            <div class="thumbnail" style="width: 100%; margin-bottom: 9%;">
                <a href="{{ photo.get_absolute_url }}">
                    <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                </a>
            </div>
        </div>
        {% endfor %}



    </div>
    <br><br>
    <div class="mx-auto">
        {% if photos.paginator.num_pages > 1 %}
        <br>
        <div class="text-center">
            {% for pg in photos.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn sm {% if photos.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

project_insta/templates/insta/album_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}album_form.html{% endblock %}

{% block content %}
<h1>Album-Photo Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
    {{ formerrors }}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
        {% endif %}
        {% csrf_token %}
        <h4>create or update album contents</h4>
        <fieldset class="card pt-3">

            <div class="form-group row">
                {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.slug|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.slug|add_class:"form-control" }}
                </div>
            </div>

        </fieldset>
        <br>

        <h4>create or update photo contents</h4>

        <fieldset class="card pt-3">

            {{ formset.management_form }}
            {% for form in formset %}
            {{ form.id }}
            {# form.album #}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <hr>
            {% endfor %}

        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

    {% endblock %}

project_insta/templates/insta/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content"
                rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

project_insta/templates/insta/myalbum.html
{% extends "base.html" %}

{% block title %}
{% if album %}
{{ album.name }} - PLATE-STUDIO
{% else %}
See Our Photos Collection - PLATE-STUDIO
{% endif %}
{% endblock %}

{% block content %}


<br>
<div>
    <h1 class="text-center my_title">BLACKVERI_0</h1>
    <br>
    <p class = "text-center">포토앨범 <br>사진을 등록해보세요</p>
</div>
<br><br>
<div class="container">
    <div class="row mx-auto">



        {% for photo in links2 %}
        <div class="my_bottom_margin col-9 col-sm-6 col-md-4 col-lg-4">
            <div class="thumbnail" style="width: 100%; margin-bottom: 9%;">
                <a href="{{ photo.get_absolute_url }}">



                    <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
            </div>
        </div>
        {% endfor %}



    </div>
    <br><br>
    <div class="mx-auto">
        {% if photos.paginator.num_pages > 1 %}
        <br>
        <div class="text-center">
            {% for pg in photos.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn sm {% if photos.number == pg %}active{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

project_insta/templates/insta/photo_detail.html
{% extends "base.html" %}
{% block title %}photo_detail.html{% endblock %}


<style>
<!--.textarea2 {-->
<!-- width: 300px;-->
<!-- height: 100px;-->
<!-- background-color: yellow;-->
<!-- font-size: 1em;-->
<!-- font-weight: bold;-->
<!-- font-family: Verdana, Arial, Helvetica, sans-serif;-->
<!-- border: 1px solid black;-->
<!--}-->









</style>


<!--            <textarea name="content" rows="3" class="textarea2"></textarea>-->

{% block content %}
<br>
<div class="row">
    <div class="col-md-8">
        <a href="{{ object.image.url }}">
            <img src="{{ object.image.url }}" style="width: 100%;">

        </a>
        <br><br>
        <div class="col-2"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{photo.voter.count}}</div>
            <a href="#" data-uri="{% url 'insta:vote_photo' photo.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">좋아요</a>
        </div>


    </div>


    <ul class="col-md-4 mt-3">

        <a>ID : {{ photo.owner.username }}</a>

<!--        <h2 class="mt-1">{{ object.title }}</h2>-->

        {% if object.description %}
        <p>{{ object.description|linebreaks }}</p>
        {% else %}
        <p>(blank)</p>
        {% endif %}
        <p class="font-italic">{{ object.upload_dt }}</p>


        {% if request.user == photo.owner %}
        <div class="my-3">
            <a href="{% url 'insta:photo_modify' photo.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'insta:photo_delete' photo.id  %}">삭제</a>
        </div>
        {% endif %}


        <form action="{% url 'insta:answer_create' photo.id %}" method="post">
            {% csrf_token %}

            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}


            <textarea name="content" rows="2" class="textarea"></textarea>
            <input type="submit" value="게시">
        </form>


        <h5>{{ photo.answer_set.count }}개의 댓이 있습니다.</h5>


        {% for answer in photo.answer_set.all %}
        <div class="card-body">
            {{ answer.content }}
            <div class="d-flex justify-content-end">

                <div class="badge badge-light p-2 text-left">

                    {% if request.user == answer.owner %}
                    <div class="my-1">
                        <a href="{% url 'insta:answer_modify' answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'insta:answer_delete' answer.id %}">삭제</a>
                    </div>
                    {% endif %}

                    <div class="mb-0">{{ answer.owner.username }} {{ answer.create_date }}</div>

<!--                    <div class="mb-2">{{ answer.owner.username }}</div>-->
<!--                    <div>{{ answer.create_date }}</div>-->


                </div>
            </div>
        </div>
        {% endfor %}


    </ul>


</div>


{% endblock %}


{% block script %}
<script type='text/javascript'>
    $(document).ready(function () {
        $(".delete").on('click', function () {
            if (confirm("정말로 삭제하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
        $(".recommend").on('click', function () {
            if (confirm("정말로 추천하시겠습니까?")) {
                location.href = $(this).data('uri');
            }
        });
    });



</script>
{% endblock %}

project_insta/templates/insta/photo_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %}photo_form.html{% endblock %}

{% block content %}
<h1>Photo Create/Update - {{user}}</h1>
<p class="font-italic">This is a creation or update form for your photo.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
<form enctype="multipart/form-data" action="" method="post" class="card pt-3">
    {% else %}
    <form action="." method="post" class="card pt-3">
        {% endif %}

        {% csrf_token %}
        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control"|attr:"autofocus" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'insta:album_add' %}" class="btn btn-outline-primary btn-sm">
                    앨범 만들기</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"}}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

    {% endblock %}