project_insta/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from common import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

project_insta/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', RedirectView.as_view(url='/insta/', permanent=True)),
    path('insta/', include('insta.urls')),
    path('common/', include('common.urls')),








    # path('', lambda request: redirect('insta/')),

    # path('', include('photo.urls')),  # '/' 에 해당되는 path
    # path('', lambda request: redirect('photo/')),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

project_insta/insta/urls.py
from django.urls import path
from insta import views, vote_views





app_name = 'insta'
urlpatterns = [


    path('', views.allPhotoAB, name='allPhotoAB'),

    path('myPhotoAB/', views.myPhotoAB, name='myPhotoAB'),
    # path('<slug:c_slug>/', views.myPhotoAB, name='myPhotoAB'),

    path('<slug:c_slug>/', views.allPhotoAB, name='album_detail'),

    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('vote/photo/<int:photo_id>/', vote_views.vote_photo, name='vote_photo'),

    path('answer/create/<int:photo_id>/', vote_views.answer_create, name='answer_create'),

    path('photo/modify/<int:photo_id>/', vote_views.photo_modify, name='photo_modify'),
    path('photo/delete/<int:photo_id>/', vote_views.photo_delete, name='photo_delete'),

    path('answer/modify/<int:answer_id>/', vote_views.answer_modify, name='answer_modify'),

    path('answer/delete/<int:answer_id>/', vote_views.answer_delete, name='answer_delete'),

    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),

    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),




    # path('<int:photo_id>/', views.detail, name='detail'),
    # # Example: /insta/album/add/
    # path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    #
    # # Example: /insta/album/change/
    # path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    #
    # # Example: /insta/album/99/update/
    # path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    #
    # # Example: /insta/album/99/delete/
    # path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    #
    # # Example: /insta/insta/add/
    # path('insta/add/', views.PhotoCV.as_view(), name='photo_add'),
    #
    # # Example: /insta/insta/change/
    # path('insta/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    #
    # # Example: /insta/insta/99/update/
    # path('insta/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    #
    # # Example: /insta/insta/99/delete/
    # path('insta/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

    # path('photo/<int:pk>/', views.PhotoDV, name='photo_detail'),

    # path('id:c_slug/id:photo_slug', views.PhotoABDetail, name = 'PhotoABDetail'),

    # path('vote/photo/<int:photo_id>/', vote_views.vote_photo, name='vote_photo'),
]

project_insta/templates/base.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">

<meta name = "description" content = "{% block metadescription %}{% endblock %}">

<!-- insta&Ans_Com CSS -->
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


<!DOCTYPE html>
<html lang="ko">

<head>

</head>

<body>

    <!-- jQuery JS -->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->



    <div class = "container">
        {% include 'navbar.html' %}
        <br>
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}





</body>

</html>

project_insta/templates/footer.html
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class = "footer navbar-fixed-bottom my_footer">
    <p class = "text-center">&copy; 고객센터 문의 ☎ 010-5223-6661</p>
</div>

project_insta/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'insta:allPhotoAB' %}">오늘의 PHOTO</a>
            </li>
        </ul>


        {% for cat in links %}
        <a class="nav-link" href="{{ cat.get_absolute_url }}">★{{cat.name}}</a>
        {% endfor %}


        {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
        {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% endif %}

    </div>
</nav>


<!--ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff-->


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarSupportedContent2"
            aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">


                <a class="nav-link" href="{% url 'insta:myPhotoAB' %}">나의사진들</a>


            </li>
        </ul>


        <a href="{% url 'insta:photo_add' %}" class="btn btn-primary">PHOTO +</a>
    </div>
</nav>