Shoppingmall-Prj/account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('register/', views.register, name='register'),
]

Shoppingmall-Prj/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('list/', views.board_list, name = 'board_list'),
    path('write/', views.board_write, name = 'board_write'),
    path('detail/<int:pk>/', views.board_detail),
]

Shoppingmall-Prj/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name = 'cart_remove'),
    path('full_delete/<int:product_id>/', views.full_remove, name = 'full_remove')
]

Shoppingmall-Prj/platestudio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url = '/shop/', permanent = True)),
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('board/', include('board.urls')),
]

if settings.DEBUG :
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Shoppingmall-Prj/search_app/urls.py
from django.urls import path
from . import views

app_name = "search_app"

urlpatterns = [
    path('', views.searchResult, name="searchResult"),
]

Shoppingmall-Prj/shop/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.allProdCat, name = 'allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name = 'products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>', views.ProdCatDetail, name = 'ProdCatDetail'),
]

Shoppingmall-Prj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html Lang = 'en'>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel = "stylesheet" href = "{% static 'css/custom.css' %}">
    <link rel = "stylesheet" href = "{% static 'css/bootstrap.min.css' %}">
    <link rel = "stylesheet" href = "{% static 'css/all.min.css' %}">
    <meta name = "description" content = "{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class = "container">
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        <br>
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}
    
    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    <script src = "{% static 'js/jquery.slim.min.js' %}"></script><script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.4.4/cjs/popper.min.js"></script>
</body>
</html>

Shoppingmall-Prj/templates/header.html
{% load static %}
<header>
    <center>
        <a href = "{% url 'shop:allProdCat' %}"><img src = "{% static 'img/logo.png' %}" alt = 'PLATE-STUDIO SHOP' style = "width:20%;"></a>
    </center>
</header>

Shoppingmall-Prj/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shop:allProdCat' %}">All Products</a>


        {% for cat1 in links %}
        <a class="nav-link" href="{{cat1.get_url}}">{{cat1.name}}</a>
        {% endfor %}


      </li>


      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href = "{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
      </li>
      {% endif %}


      {% if not request.session.user %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:register' %}">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:login' %}">Login</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
        </li>        
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href = "{% url 'board:board_list' %}">FAQ</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name = "q">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>